spring:
  application:
    name: sertao-api

  datasource:
    url: jdbc:postgresql://localhost:5432/sertao
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Vyni1995

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

